//
// Credential.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Every object can have one or more credential(s) associated with it. (i.e. &#x60;my_researcher.credentials &#x3D; [&#39;person A&#39;, &#39;person B&#39;, &#39;api A&#39;&#39;, &#39;person C&#39;, &#39;api B&#39;]&#x60;) */

@objc public class Credential: NSObject, Codable { 

    /** The root object this credential is attached to. The scope of this credential is limited to the object itself and any children. */
    public var origin: String?
    /** Username or machine-readable public key (access). */
    public var accessKey: String?
    /** SALTED HASH OF Password or machine-readable private key (secret). */
    public var secretKey: String?
    /** The user-visible description of the credential. */
    public var _description: String?

    public init(origin: String?, accessKey: String?, secretKey: String?, _description: String?) {
        self.origin = origin
        self.accessKey = accessKey
        self.secretKey = secretKey
        self._description = _description
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case origin
        case accessKey = "access_key"
        case secretKey = "secret_key"
        case _description = "description"
    }

}
