//
// Document.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



@objc public class Document: NSObject, Codable { 

    public var meta: Metadata?
    public var data: [Any]?

    public init(meta: Metadata?, data: [Any]?) {
        self.meta = meta
        self.data = data
    }

}
