//
// DurationIntervalLegacy.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



@objc public class DurationIntervalLegacy: NSObject, Codable { 

    public var repeatType: String?
    /** The UNIX Epoch date-time representation: number of milliseconds since 1/1/1970 12:00 AM. */
    public var date: Double?
    public var customTimes: [Any]?

    public init(repeatType: String?, date: Double?, customTimes: [Any]?) {
        self.repeatType = repeatType
        self.date = date
        self.customTimes = customTimes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case repeatType = "repeat_type"
        case date
        case customTimes = "custom_times"
    }

}
