//
// DurationInterval.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



@objc public class DurationInterval: NSObject, Codable { 

    /** The UNIX Epoch date-time representation: number of milliseconds since 1/1/1970 12:00 AM. */
    public var start: Double?
    public var interval: [Any]?
    public var repeatCount: Int64?
    public var repeatCountNum: NSNumber? {
        get {
            return repeatCount as NSNumber?
        }
    }
    /** The UNIX Epoch date-time representation: number of milliseconds since 1/1/1970 12:00 AM. */
    public var end: Double?

    public init(start: Double?, interval: [Any]?, repeatCount: Int64?, end: Double?) {
        self.start = start
        self.interval = interval
        self.repeatCount = repeatCount
        self.end = end
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case start
        case interval
        case repeatCount = "repeat_count"
        case end
    }

}
