//
// DynamicAttachment.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



@objc public class DynamicAttachment: NSObject, Codable { 

    /** The key. */
    public var key: String?
    /** A globally unique reference for objects. */
    public var from: String?
    /** Either \&quot;me\&quot; to apply to the attachment owner only, the ID of an object owned  by the attachment owner, or a string representing the child object type to apply to. */
    public var to: String?
    /** The API triggers that activate script execution. These will be event stream types  or object types in the API, or, if scheduling execution periodically, a cron-job string  prefixed with \&quot;!\&quot; (exclamation point). */
    public var triggers: [Any]?
    /** The script language. */
    public var language: String?
    /** The script contents. */
    public var contents: String?
    /** The script requirements. */
    public var requirements: [Any]?

    public init(key: String?, from: String?, to: String?, triggers: [Any]?, language: String?, contents: String?, requirements: [Any]?) {
        self.key = key
        self.from = from
        self.to = to
        self.triggers = triggers
        self.language = language
        self.contents = contents
        self.requirements = requirements
    }

}
