//
// Metadata.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



@objc public class Metadata: NSObject, Codable { 

    public var access: AccessCitation?

    public init(access: AccessCitation?) {
        self.access = access
    }

}
