//
// ModelError.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



@objc public class ModelError: NSObject, Codable { 

    public var error: String?

    public init(error: String?) {
        self.error = error
    }

}
