//
// Participant.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** A participant within a study; a participant cannot be enrolled in more than one study at a time. */

@objc public class Participant: NSObject, Codable { 

    /** A globally unique reference for objects. */
    public var _id: String?
    /** The researcher-provided study code for the participant. */
    public var studyCode: String?
    /** The participant&#39;s selected language code for the LAMP app. */
    public var language: String?
    /** The participant&#39;s selected theme for the LAMP app. */
    public var theme: String?
    /** The participant&#39;s emergency contact number. */
    public var emergencyContact: String?
    /** The participant&#39;s selected personal helpline number. */
    public var helpline: String?

    public init(_id: String?, studyCode: String?, language: String?, theme: String?, emergencyContact: String?, helpline: String?) {
        self._id = _id
        self.studyCode = studyCode
        self.language = language
        self.theme = theme
        self.emergencyContact = emergencyContact
        self.helpline = helpline
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case _id = "id"
        case studyCode = "study_code"
        case language
        case theme
        case emergencyContact = "emergency_contact"
        case helpline
    }

}
