//
// Researcher.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



@objc public class Researcher: NSObject, Codable { 

    /** A globally unique reference for objects. */
    public var _id: String?
    /** The name of the researcher. */
    public var name: String?
    /** The email address of the researcher. */
    public var email: String?
    /** The physical address of the researcher. */
    public var address: String?
    /** The set of all studies conducted by the researcher. */
    public var studies: [Any]?

    public init(_id: String?, name: String?, email: String?, address: String?, studies: [Any]?) {
        self._id = _id
        self.name = name
        self.email = email
        self.address = address
        self.studies = studies
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case _id = "id"
        case name
        case email
        case address
        case studies
    }

}
