//
// SensorEvent.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** An event generated by a participant interacting with the LAMP app. */

@objc public class SensorEvent: NSObject, Codable { 

    /** The UNIX Epoch date-time representation: number of milliseconds since 1/1/1970 12:00 AM. */
    public var timestamp: Double?
    /** The type of the sensor event. */
    public var sensor: String?
    /** The item information recorded within the sensor event. */
    public var data: Any?

    public init(timestamp: Double?, sensor: String?, data: Any?) {
        self.timestamp = timestamp
        self.sensor = sensor
        self.data = data
    }

}
