//
// SensorSpec.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** The SensorSpec determines the parameters of generated SensorEvents. */

@objc public class SensorSpec: NSObject, Codable { 

    /** The name of the sensor. */
    public var name: String?
    /** The data definition of a SensorSpec. */
    public var settingsSchema: Any?

    public init(name: String?, settingsSchema: Any?) {
        self.name = name
        self.settingsSchema = settingsSchema
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case name
        case settingsSchema = "settings_schema"
    }

}
