name: LAMP
targets:
  LAMP:
    type: framework
    platform: iOS
    deploymentTarget: "14.0"
    sources: [LAMP]
    info:
      path: ./Info.plist
      version: 1.0.0
    settings:
      APPLICATION_EXTENSION_API_ONLY: true
    scheme: {}
    
