//
// Sensor.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
//import AnyCodable

/** A sensor that may or may not be available on a physical device. */
public struct Sensor: Codable {

    /** A globally unique reference for objects. */
    public var id: String?
    /** A globally unique reference for objects. */
    public var spec: String?
    /** The name of the sensor. */
    public var name: String?
    /** The configuration settings for the sensor. */
    public var settings: AnyCodable?

    public init(id: String? = nil, spec: String? = nil, name: String? = nil, settings: AnyCodable? = nil) {
        self.id = id
        self.spec = spec
        self.name = name
        self.settings = settings
    }

}

