//
// AccessCitation.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct AccessCitation: Codable {

    public var _in: String?
    public var at: String?
    /** The UNIX Epoch date-time representation: number of milliseconds since 1/1/1970 12:00 AM. */
    public var on: Double?
    public var by: String?

    public init(_in: String? = nil, at: String? = nil, on: Double? = nil, by: String? = nil) {
        self._in = _in
        self.at = at
        self.on = on
        self.by = by
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case _in = "in"
        case at
        case on
        case by
    }

}

