//
// Document.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
//import AnyCodable

public struct Document: Codable {

    public var meta: Metadata?
    public var data: [AnyCodable]?

    public init(meta: Metadata? = nil, data: [AnyCodable]? = nil) {
        self.meta = meta
        self.data = data
    }

}

