//
// Metadata.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct Metadata: Codable {

    public var access: AccessCitation?

    public init(access: AccessCitation? = nil) {
        self.access = access
    }

}

