//
// ModelError.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct ModelError: Codable {

    public var error: String?

    public init(error: String? = nil) {
        self.error = error
    }

}

