//
// Researcher.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct Researcher: Codable {

    /** A globally unique reference for objects. */
    public var id: String?
    /** The name of the researcher. */
    public var name: String?
    /** The email address of the researcher. */
    public var email: String?
    /** The physical address of the researcher. */
    public var address: String?
    /** The set of all studies conducted by the researcher. */
    public var studies: [Any]?

    public init(id: String? = nil, name: String? = nil, email: String? = nil, address: String? = nil, studies: [Any]? = nil) {
        self.id = id
        self.name = name
        self.email = email
        self.address = address
        self.studies = studies
    }

}

