//
// SensorSpec.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

/** The SensorSpec determines the parameters of generated SensorEvents. */
public struct SensorSpec: Codable {

    /** The name of the sensor. */
    public var name: String?
    /** The data definition of a SensorSpec. */
    public var settingsSchema: AnyCodable?

    public init(name: String? = nil, settingsSchema: AnyCodable? = nil) {
        self.name = name
        self.settingsSchema = settingsSchema
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case name
        case settingsSchema = "settings_schema"
    }

}

