//
// SensorEvent.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

/** An event generated by a participant interacting with the LAMP app. */
public struct SensorEvent: Codable {

    /** The UNIX Epoch date-time representation: number of milliseconds since 1/1/1970 12:00 AM. */
    public var timestamp: Double?
    /** The type of the sensor event. */
    public var sensor: String?
    /** The item information recorded within the sensor event. */
    public var data: AnyCodable?

    public init(timestamp: Double? = nil, sensor: String? = nil, data: AnyCodable? = nil) {
        self.timestamp = timestamp
        self.sensor = sensor
        self.data = data
    }

}

