//
// TemporalSlice.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
//import AnyCodable

/** A specific sub-detail of a &#x60;ActivityEvent&#x60; that contains specific  interaction information that comprises the parent &#x60;ActivityEvent&#x60;. */
public struct TemporalSlice: Codable {

    /** The item that was interacted with; for example, in a Jewels game, the  corresponding alphabet, or in a survey, the question index. */
    public var item: AnyCodable?
    /** The value of the item that was interacted with; in most games,  this field is  &#x60;null&#x60;, but in a survey, this field is the question  choice index. */
    public var value: AnyCodable?
    /** The type of interaction that for this detail; for example, in  a Jewels game,  &#x60;none&#x60; if the tapped jewel was  incorrect, or &#x60;correct&#x60; if it was correct, or in  a  survey, this field will be &#x60;null&#x60;. */
    public var type: String?
    /** The time difference from the previous detail or the  start of the parent result. */
    public var duration: Int64?
    /** The level of activity for this detail; for example, in  games with multiple  levels, this field might be &#x60;2&#x60; or  &#x60;4&#x60;, but for surveys and other games this field  will be &#x60;null&#x60;. */
    public var level: Int64?

    public init(item: AnyCodable? = nil, value: AnyCodable? = nil, type: String? = nil, duration: Int64? = nil, level: Int64? = nil) {
        self.item = item
        self.value = value
        self.type = type
        self.duration = duration
        self.level = level
    }

}

